# Generated by Django 5.0 on 2023-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_task_datetime_alter_task_deadline_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created",
        ),
    ]
