# Generated by Django 5.0 on 2023-12-31 19:35

import django.db.models.deletion
import django.views.generic.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_rename_datetime_task_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatusUpdateView",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todo.task",
                    ),
                ),
            ],
            bases=("todo.task", django.views.generic.base.View),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
