# Generated by Django 5.0 on 2023-12-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_rename_datetime_task_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
